# Begin from the base offical Python image on DockerHub

# Set the working directory to /fastapi-server

# Copy the current directory contents into the container at /fastapi-server

# Install the two packages that you did in fastapi exercise 1: fastapi and uvicorn[standard]

# Run the server when the container launches with the ENTRYPOINT command
# Note: Launch the server at the host 0.0.0.0 so that outside request from your computer can reach the container
# https://pythonspeed.com/articles/docker-connection-refused/
# https://stackoverflow.com/questions/59179831/docker-app-server-ip-address-127-0-0-1-difference-of-0-0-0-0-ip 
