version: '3.7'
services:
  fastapi-backend:
    container_name: docker-fastapi
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
  nginx:
    depends_on:
      - fastapi-backend
    container_name: docker-proxy
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
